// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WcagAnalyzer.Infrastructure.Data;

#nullable disable

namespace WcagAnalyzer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("WcagAnalyzer.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnalysisRequests");
                });

            modelBuilder.Entity("WcagAnalyzer.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HelpUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlElement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("WcagAnalyzer.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("WcagAnalyzer.Domain.Entities.AnalysisRequest", "AnalysisRequest")
                        .WithMany("Results")
                        .HasForeignKey("AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRequest");
                });

            modelBuilder.Entity("WcagAnalyzer.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
