import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-terms',
  imports: [RouterLink],
  template: `
    <div class="legal-page">
      <div class="legal-container">
        <a class="legal-back" routerLink="/">← Back</a>
        <h1>Terms of Service</h1>
        <p class="legal-date">Last updated: April 2025</p>

        <h2>Service description</h2>
        <p>WCAG Analyzer provides automated accessibility scanning of publicly accessible websites and delivers the results as a PDF report to the email address provided at checkout.</p>

        <h2>Payments</h2>
        <p>Payments are processed securely by Stripe. All prices are in USD and include applicable taxes where required by law.</p>

        <h2>Refund policy</h2>
        <p>Because our service delivers a digital product (a PDF report), all sales are final once the scan has been completed and the report delivered. If you did not receive your report due to a technical error on our side, contact us and we will re-send it or issue a full refund.</p>

        <h2>Acceptable use</h2>
        <p>You may only submit URLs for websites you own or have explicit permission to scan. Submitting URLs of websites you do not control is prohibited.</p>

        <h2>Liability</h2>
        <p>Our reports are generated by automated tools and are provided for informational purposes. They do not constitute legal advice. We are not liable for any penalties, fines, or damages arising from use of this service.</p>

        <h2>Contact</h2>
        <p>Questions about these terms? Email us at <a href="mailto:hello@wcag-analyzer.com">hello@wcag-analyzer.com</a>.</p>
      </div>
    </div>
  `,
  styleUrl: './app.scss'
})
export class Terms {}
